### ISSUE TITLE
How to disable only specific dates in date-picker

### ISSUE THREAD

**Issue by visheshdh** [accdc/tsg#19]
I have requirement to disable all the public holidays of UK in the date. I'll be having an array of dates that need to be disabled. Any idea how this can be achieved? Any kind of help is most welcomed.

**Comment by accdc** [comment]
Hi,
Yes of course, there are examples of this within this GitHub project.

Once you clone or download the repo: https://github.com/whatsock/tsg

Look within the folder: `Coding Arena\ARIA Date Pickers`, and review the ReadMe.txt file contained within that folder.

Towards the bottom of the ReadMe, there is a section named "Additional Programmatic Control", which lists the following methods for performing the actions you would like to do.

`dc.setDayDisabled(dc, dateObj, isDisabled)`

`dc.setMonthDisabled(dc, dateObj, isDisabled)`

`dc.setDayOfWeekDisabled(dc, dateObj, daysOfWeekArray, isDisabled)`

`dc.setWeekdaysDisabled(dc, dateObj, isDisabled)`

`dc.setWeekendsDisabled(dc, dateObj, isDisabled)`

`dc.clearAllDisabled(dc)`

**Comment by visheshdh** [comment]
Hello,
Thanks a lot for your response. I am able to disable specific dates now. Actually We need to disable all public holidays in UK. setDayDisabled function only accepts one date object to be disabled. I could not find a function that accepts an array of dates that need to be disabled. Is there any such function? If not then I can run a loop and call setDayDisabled.

**Comment by accdc** [comment]
Hi,
Actually yes, though it's a bit of a pain to do it, which is why it's not documented generally.

Basically, the disabled date tracking is done within the "range" object within the instantiated calendar object, so you can technically apply full disabled date ranges to all date objects, or pick and choose individual ones as you need by dynamically adding these.

To see how this is done, look at the function named "setDayDisabled" within the file calendar_generator.js.

You can then set up a function to merge all of the disabled dates you want at one time this way.

**Comment by visheshdh** [comment]
Thank you so much for your help.

**Comment by accdc** [comment]
No problem. :) 

As a quick note, I pushed a new version of the Calendar Module within the TSG earlier today, which adds additional mainstream support for screen reader accessibility. I recommend using this one instead of the one you are currently using so these improvements will automatically be available within your own projects.

The update requires no coding changes, all of the back-end processing is the same, so all you would need to do is replace the calendar_generator.min.js file with the new one, and that will do the trick.

All the best,
Bryan
