### ISSUE TITLE
Open Calendar on page load

### ISSUE THREAD

**Issue by visheshdh** [accdc/tsg#20]
Hi Bryan,

We have a requirement to open the calendar as soon as the page loads. Basically the user does not have to click on the datepicker in order to open because it will be open by default from the beginning.

I tried using openOnFocus: true but it did not work. Is there anything else that need to be changed?
Or do I need to override some method and call dc.open() myself? if so which function do i override that accepts dc as argument? 
Any help is really appreciated.

Thanks.

**Comment by accdc** [comment]
Hi,
I'm happy to help.

So I understand correctly, when the page loads, do you have an input field that the date string will be saved to, similar to the ones in the examples?

**Comment by visheshdh** [comment]
Hi Bryan,
Yes we do have an input field. Below is the code. We are using this input field and onblur or onfocus of href we use datepicker ref to store the value in state.
<div >
                            <input 
                                type="text" id="itemName_basic1__input"
                                name="itemName_basic1__input"
                                value={this.state.date || ""}
                                onBlur={(e) => this.updateCurrentElemValue(e, model, sessionKey) }
                                ref="datePicker"
                                onChange={(e) => this.updateCurrentElemValue(e, model, sessionKey) }
                                onClick = {(e) => this.updateCurrentElemValue(e, model, sessionKey) }
                                autoComplete="off" placeholder="DD/MM/YYYY"
                            />
                            <svg className="c-icon c-icon--medium c-icon--error u-hide-init" aria-hidden="true" focusable="false" />

                            <a href="JavaScript:void(0)"
                                aria-expanded="false"
                                onBlur={()=> {this.refs.datePicker.focus(); this.refs.datePicker.blur()}}>
                                <span >
                                    Select date
                                </span>
                            </a>
                        </div>

**Comment by accdc** [comment]
Hi,
The easiest way to do this, is to simply configure the instantiated calendar object whenever you want to set a new date, which you can do from any event handler. E.G window.onload, etc.

Every time you setup a new calendar binding using $A.setCalendar(...), the first parameter you pass will be the string id of that calendar instance. This instance is always in memory, even when it's not open and rendered visually. So, you can use the id to get a reference of this instance at any time and configure the calendar using it's id, like so.

```
var dc = $A.reg["myCalendarId"];
```

Then, you can use the built-in configuration methods to set the date however you like before the calendar is opened.


After you set the calendar options that you want to update, then execute the open method like so.

```
dc.open();
```

It's important to keep in mind though, to ensure accessibility for screen reader users, the calendar will automatically grab keyboard focus as soon as it renders, so you should be careful when doing this, so that the functionality will be intuitive to non-sighted screen reader users when encountered.

**Comment by visheshdh** [comment]
Hi Bryan,
Thanks a lot for your input. We are successfully able to open our calendar on page load. However the client wishes to keep the calendar open even after selecting a particular date. Basically the calendar must never close. I went through the docs but I doubt if there is an easy way to achieve this like passing a parameter like 'alwaysOpen' etc. Runafterclose can also not be used in this case coz we need to maintain the calendar always opened. 

Please suggest some way to achieve this. Thanks a ton for all the help you have provided till now.

**Comment by visheshdh** [comment]
Hi Bryan,
Thanks a lot for your input. We are successfully able to open our calendar
on page load. However the client wishes to keep the calendar open even
after selecting a particular date. Basically the calendar must never close.
I went through the docs but I doubt if there is an easy way to achieve this
like passing a parameter like 'alwaysOpen' etc. Runafterclose can also not
be used in this case coz we need to maintain the calendar always opened.

Please suggest some way to achieve this. Thanks a ton for all the help you
have provided till now.
