### ISSUE TITLE
Keep Date-picker always open

### ISSUE THREAD

**Issue by visheshdh** [accdc/tsg#21]
Hi Bryan,

Really Really sorry to raise this as an issue here.
In my project the client wishes to keep the calendar open even
after selecting a particular date. Basically the calendar must never close.
I went through the docs but I doubt if there is an easy way to achieve this
like passing a parameter like 'alwaysOpen' etc.  When I tried dc.open() in runAfterClose it did prevent the calendar from closing but the problem was that when I change the month it starts giving  an error that 'name' of undefined. I guess there are some events that are triggered after closing the calendar which are not getting triggered.

Also on a different note, our team have decided to create a new date-picker using whatsock library.
Since most of us are react developers it would be really helpful if you can tell some example repo or docs to integrate whatsock in react.

Please suggest some way to achieve both the cases. Any advice is much appreciated . Thanks a ton for all the help you have provided till now.

**Comment by LaurenceRLewis** [comment]
Hi @visheshdh The beta accdc REACT might help. 

accdc-react

BETA release of AccDC 4X + React for building advanced accessible ARIA widgets within the React IDE
https://github.com/WhatSock/accdc-react

**Comment by accdc** [comment]
Hi,
I apologize for the delay in getting back, yes indeed, the AccDC 4X project is the best bet for React IDE integration. 

As a quick note, I've been updating the calendar module in the last couple weeks with some performance and accessibility improvements, and will be migrating these into the AccDC 4X for React project within the next week or so, so please subscribe to that project so that you will be updated when this upload is available.

**Comment by accdc** [comment]
Let me look into the always open possibilities this next week. I'll get back as soon as I learn more.

**Comment by accdc** [comment]
Hi,
Thank you again for your patience, I just pushed a date picker update that includes some additional support for accessibility, plus some performance enhancements.

Regarding making the calendar remain open, once you trigger the calendar so that it opens, you can lock it in its open position by setting DC.lock = true. This is an AccDC API feature, and will simply lock the object in its currently rendered state.

You will also need to set a custom function to run when a date is activated, which can be done within the initial setup script as well. This will allow you to save the date wherever you like in whatever format you want, and then move focus accordingly without closing the calendar. There are examples of setting a custom function for doing this within the React project at:
https://github.com/whatsock/accdc-react

**Comment by accdc** [comment]
Closing this issue as fixed for now. Please reopen if the feature is still unresolved.
