### ISSUE TITLE
Date Picker (with Disabled Date Ranges) - disabled dates are not indicated to the user in Windows HCM with keyboard-only operation

### ISSUE THREAD

**Issue by OwenEdwards** [accdc/tsg#3]
In the [ARIA Date Picker (with Disabled Date Ranges)/demo.htm](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20%28with%20Disabled%20Date%20Ranges%29/demo.htm) example, color is used to "gray out" dates which are disabled, and they also have `title="Disabled"` and `aria-disabled="true"`.

If I use IE's Accessibility Settings to "_Ignore colors specified on webpages_" (to simulate Windows High Contrast Mode), and then use keyboard-only access to open the Date Picker and move focus to a disabled date, the `title` tooltip is not displayed and the date is not visually different from other dates. The only difference is that it cannot be activated/selected.

I think there needs to be another visual indication that this date is not valid - that indication should not depend on CSS, ARIA or the `title` attribute tooltip for operation.

Thoughts?

**Comment by accdc** [comment]
It's an interesting idea, but extremely challenging to implement for what seems to be little in the way of gain for accessibility.

For example, if CSS can't be used to provide a visual difference between enabled versus disabled dates, and the only purpose is to convey this information visually for people who are not using CSS and who are not using a screen reader and who are not also using a mouse, then the JavaScript would need to be changed to first detect when CSS is disabled, then manually replace all disabled dates with something else such as a special character written directly into the DOM, or an image would have to be inserted programmatically into all of these dates instead.

If using the special character injection, it's not certain that the person would know what the symbol meant either, resulting in the same problem, and an injected image would not be scalable because it would require a server side dependency that could easily be forgotten when developers implement this widget within enterprise apps.

So it would take a huge amount of reengineering and bloat the code significantly to accomplish this, when it doesn't really address an accessibility issue exactly. E.G The user can still choose the date they wish, it simply won't do anything when Enter is pressed on a disabled date.

Hopefully this makes sense. Please let me know your thoughts. :)

**Comment by OwenEdwards** [comment]
Makes sense!
