### ISSUE TITLE
Combobox scrolls the page when down arrow key pressed

### ISSUE THREAD

**Issue by kalyan1102** [accdc/tsg#7]
When I am pressing down arrow key while focused on input the page is getting scrolled to the top.

**Comment by accdc** [comment]
Hi, I'll be happy to look into it. Can you identify which OS and browser/version you are using when this occurs? Thanks, Bryan

**Comment by kalyan1102** [comment]
Hi Bryan, 

Thanks a lot for your reply. I have used latest Chorme with windows 7 and 10. Same thing happening with Chrome on Mac OSX Maverick.

Thanks
Kalyan

**Comment by GovindaAgarwal** [comment]
I did check in safari / Mac & iOS mobile as well and it seems to be same jumping issue

**Comment by kalyan1102** [comment]
Hi Briyan,

I have commented out this line and the page is not jumping anymore. Though I dont want to change the library code is there any other way to disable it?
// u.scrollIntoView();

Thanks in advance.

Kalyan

**Comment by accdc** [comment]
Hi,
Thanks, I thought this would be the issue. This has to do with the unreliable browser support for .scrollIntoView.
E.G https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

This is unfortunate, because without it, the scrollability for offscreen options won't automatically come into view when selected using the arrow keys.

Even so though, when I built the Combobox module, I made this an overridable function so you can change this as needed within your setup file so that commenting out the module code line isn't necessary.

This can be done using the instantiated combobox instance within the setup js file (setup.js), like so:

myCombobox.scrollIntoView = function(node){
// Do nothing or choose to do something with node which is the selected option element
};

I'm looking into a more cross browser friendly method for doing this in the meantime, so will post an update here when I get this put into the live code.

:)

**Comment by kalyan1102** [comment]
Bryan,

Thanks a lot. this helps!

Thanks
Kalyan

**Comment by accdc** [comment]
Hi, I believe I've fixed the bug, and have updated the ARIA Combobox module files plus the relevant setup.js files. Please let me know if that corrects the issue.

**Comment by accdc** [comment]
Hi, This fix was tested on IE11, Firefox, and Chrome, and it appears to now work correctly when using jQuery, Dojo, and MooTools. Please open a new issue if you encounter any other issues. Thanks again. :)
